import { Inter } from "next/font/google";
import Head from 'next/head';
import "./globals.css";
import NavBar from "@/components/NavBar";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html style={{minHeight: '100%'}}lang="en">
      <Head>
        <link href="https://fonts.googleapis.com/css?family=Staatliches" rel="stylesheet" />
      </Head>
      <body >
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
